on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - uses: pre-commit/action@v3.0.0
      - name: .NET Publish
        run: |
          DOTNET_VERSION=${GITHUB_REF_NAME#v*}
          echo $DOTNET_VERSION
          dotnet publish src/PercepSync/PercepSync.csproj -p:Version=$DOTNET_VERSION
      - uses: svenstaro/upload-release-action@v2
        with:
          file: src/PercepSync/bin/Debug/net7.0/linux-x64/publish/PercepSync
